version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: "iamaul/game-currency-whim:latest"
    container_name: game-currency-whim
    restart: on-failure
    env_file: .env
    depends_on:
      - mysql
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - ./.env:/app/.env

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      # - MYSQL_ROOT_HOST=${DB_HOSTNAME} 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - default
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: "iamaul/nginx:latest"
    container_name: nginx
    restart: unless-stopped
    networks:
      - default
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs/game-currency.whim.iamaul.me.crt:/etc/nginx/certs/game-currency.whim.iamaul.me.crt
      - ./nginx/certs/game-currency.whim.iamaul.me.key:/etc/nginx/certs/game-currency.whim.iamaul.me.key

volumes:
  mysql-db:

networks:
  default:
    external:
      name: gateway